### ISSUE TITLE
Still compatible?

### ISSUE THREAD

**Issue by flip111** [westonganger/chosen-material-theme#3]
Since there has not been in update in 4 years i was wondering if this theme is still compatible with the latest chosen.

By the way .. a screenshot or demo page would be nice.

**Comment by westonganger** [comment]
Yes its still compatible. Dont ever judge compatibility on last update time. Not all code needs to be updated over time. Chosen remains almost unchanged over-time, as chosen is perfectly working in its current state and has a large legacy userbase.

**Comment by flip111** [comment]
excellent, thank you
